# Generated by Django 4.2.1 on 2023-05-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
            ],
        ),
    ]
