# Generated by Django 4.2.1 on 2023-05-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0002_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Client1',
        ),
    ]
