# Generated by Django 4.2.1 on 2023-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0003_AddedClient1Table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client1',
            name='created_at',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
